{
 "title": "Multi-Storage Client",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_source", "label": "Metrics Source", "query": "prometheus" },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(multistorageclient_version)"
   },
   {
    "name": "provider",
    "label": "Provider",
    "query": "label_values(multistorageclient_provider)"
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": "label_values(multistorageclient_operation)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(multistorageclient_status)"
   },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   { "name": "node", "label": "Node", "query": "label_values(node)" }
  ]
 },
 "panels": [
  { "title": "Aggregates", "type": "row", "gridPos": { "x": 0, "y": 0, "h": 1, "w": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "An [aggregate](https://en.wikipedia.org/wiki/Aggregate_function) is a summary of an underlying distribution.\n\nThese preserve global (i.e. aggregate) information at the expense of local (i.e. per-sample) information."
   }
  },
  {
   "title": "Request – Sum",
   "type": "timeseries",
   "description": "The request sum by operation for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation) (increase(multistorageclient_request_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}}"
    }
   ]
  },
  {
   "title": "Request – Rate",
   "type": "timeseries",
   "description": "The request rate by operation for matching samples.\n\nThis is the average (i.e. not instantaneous) request rate for each interval.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation) (rate(multistorageclient_request_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}}"
    }
   ]
  },
  {
   "title": "Response – Sum",
   "type": "timeseries",
   "description": "The response sum by operation and status for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation, multistorageclient_status) (increase(multistorageclient_response_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}} – {{multistorageclient_status}}"
    }
   ]
  },
  {
   "title": "Response – Rate",
   "type": "timeseries",
   "description": "The response rate by operation and status for matching samples.\n\nThis is the average (i.e. not instantaneous) response rate for each interval.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation, multistorageclient_status) (rate(multistorageclient_response_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}} – {{multistorageclient_status}}"
    }
   ]
  },
  {
   "title": "Data Size – Sum",
   "type": "timeseries",
   "description": "The data size sum by operation and status for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation, multistorageclient_status) (increase(multistorageclient_data_size_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}} – {{multistorageclient_status}}"
    }
   ]
  },
  {
   "title": "Data Size – Rate",
   "type": "timeseries",
   "description": "The data rate by operation and status for matching samples.\n\nThis is the average (i.e. not instantaneous) data rate for each interval.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(multistorageclient_operation, multistorageclient_status) (rate(multistorageclient_data_size_sum{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{multistorageclient_operation}} – {{multistorageclient_status}}"
    }
   ]
  },
  { "title": "Empirical Distributions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "An [empirical distribution](https://en.wikipedia.org/wiki/Empirical_distribution_function) is a sampled subset of an underlying distribution. If the sampling rate is high enough, this is equal to the true distribution.\n\nThese preserve local (i.e. per-sample) information at the expense of global (i.e. aggregate) information when the sampling rate is __NOT__ high enough (most deployments)."
   }
  },
  {
   "title": "Data Size – Empirical Distribution",
   "type": "heatmap",
   "description": "The data size empirical distribution for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}"
    }
   ]
  },
  {
   "title": "Data Size – Empirical Distribution Percentiles",
   "type": "timeseries",
   "description": "The data size empirical distribution percentiles for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "quantile(1, multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile(0.999, multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99.9"
    },
    {
     "expr": "quantile(0.99, multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.9, multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.5, multistorageclient_data_size{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Latency – Empirical Distribution",
   "type": "heatmap",
   "description": "The latency empirical distribution for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}"
    }
   ]
  },
  {
   "title": "Latency – Empirical Distribution Percentiles",
   "type": "timeseries",
   "description": "The latency empirical distribution percentiles for matching samples.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(1, multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile(0.999, multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99.9"
    },
    {
     "expr": "quantile(0.99, multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.9, multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.5, multistorageclient_latency{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Data Rate – Empirical Distribution",
   "type": "heatmap",
   "description": "The data rate empirical distribution for matching samples.\n\nThis is the average (i.e. not instantaneous) data rate for each sample.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"}"
    }
   ]
  },
  {
   "title": "Data Rate – Empirical Distribution Percentiles",
   "type": "timeseries",
   "description": "The data rate empirical distribution percentiles for matching samples.\n\nThis is the average (i.e. not instantaneous) data rate for each sample.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile(1, multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile(0.999, multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99.9"
    },
    {
     "expr": "quantile(0.99, multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.9, multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.5, multistorageclient_data_rate{multistorageclient_version=~\"${version}\", multistorageclient_provider=~\"${provider}\", multistorageclient_operation=~\"${operation}\", multistorageclient_status=~\"${status}\", cluster=~\"${cluster}\", node=~\"${node}\"})",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}